apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newName: rakusa/reqs-payload 
  newTag: x86_64-45efc1afe4ab0e749e9c2505b7dcc7ff2b3869f6
- name: quay.io/kata-containers/kata-deploy
  newName: rakusa/device-qemu
  newTag: kata-containers-latest

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      # - name: "kata-clh"
      #   snapshotter: "tardev"
      - name: "kata-qemu"
        snapshotter: "tardev"
      # - name: "kata-qemu-tdx"
      #   snapshotter: "nydus"
      # - name: "kata-qemu-sev"
      #   snapshotter: "nydus"
      - name: "kata-qemu-snp"
        snapshotter: "tardev"
    - op: add
      path: /spec/config/defaultRuntimeClassName
      value: "kata-qemu"
    - op: add
      path: /spec/config/debug
      value: false
    - op: add
      path: /spec/config/environmentVariables
      value:
        # It means that we're relying on the cluster to already have
        # containerd v1.7+ running.  If you know for sure that's not
        # the case, please, set this variable to `true`
        - name: "INSTALL_OFFICIAL_CONTAINERD"
          value: "false"
        - name: "INSTALL_NYDUS_SNAPSHOTTER"
          value: "false"
        - name: "INSTALL_TARDEV_SNAPSHOTTER"
          value: "true"
        - name: "SNAPSHOTTER"
          value: "tardev"
  target:
    kind: CcRuntime
